name: Builds

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: rp-bf.rs / ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {os: "ubuntu-latest", url: "https://github.com/yrp604/bochscpu-build/releases/download/v0.3/bochscpu-build-ubuntu-latest-x64.zip" }
        - {os: "windows-latest", url: "https://github.com/yrp604/bochscpu-build/releases/download/v0.3/bochscpu-build-windows-latest-x64.zip" }
  
    steps:
      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout rp-bf.rs
        uses: actions/checkout@v3
        with:
          path: rp-bf.rs

      - name: Checkout bxcpu
        uses: actions/checkout@v3
        with:
          repository: yrp604/bochscpu
          path: bochscpu

      - name: Download bxcpu-build artefacts
        run: |
          cd bochscpu
          curl -L ${{ matrix.config.url }} -o bxcpu-build.zip
          7z x bxcpu-build.zip
          cd ..

      - name: Build
        run: |
          cd rp-bf.rs
          cargo build --example p2o-miami22-finders
          cargo build --release --example p2o-miami22-finders

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: p2o-miami22-finders.dbg.${{ matrix.config.os }}
          path: |
            rp-bf.rs/target/debug/examples/p2o_miami22_finders*
            rp-bf.rs/win10_ux64.json

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: p2o-miami22-finders.${{ matrix.config.os }}
          path: |
            rp-bf.rs/target/release/examples/p2o_miami22_finders*
            rp-bf.rs/win10_ux64.json
